PREFIX rso: <http://rdf.biosemantics.org/ontologies/rsa#>
PREFIX so: <http://purl.obolibrary.org/obo/>
PREFIX hg19: <http://rdf.biosemantics.org/data/genomeassemblies/hg19#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX geneonto: <http://www.geneontology.org/formats/oboInOwl#>
  
SELECT DISTINCT ?gene (str(?cageClusterLabel) as ?tssName) ?sample ?tissueType (str(?tissueTypeLabel) as ?tissueTypeName) ?tpmValue  where {

  VALUES (?gene) { (<http://www.ncbi.nlm.nih.gov/gene/?GENEID> ) } 
  VALUES (?tissueType) {?TISSUETYPE} 
  
  GRAPH ?rikenAssertion2 {      
    ?cageCluster rso:is_observation_of ?tssRegion.
    ?tssRegion a so:SO_0001240;
               so:so_associated_with ?gene.  
  }
  VALUES (?tissueType) {(<http://purl.obolibrary.org/obo/UBERON_0000178>) (<http://purl.obolibrary.org/obo/UBERON_0000955>)}
  GRAPH ?rikenAssertion3  
  {    
    ?cageCluster obo:so_associated_with ?measurementValues ;            
      rso:observed_in ?sample .        
    ?measurementValues obo:IAO_0000004 ?tpmValue .  
  }
  ?cageCluster rdfs:label ?cageClusterLabel 
  
  {
    ?adultHuman rdfs:subClassOf obo:FF_0000998 ;        
      rdfs:subClassOf obo:FF_0000210 ;        
      rdfs:label ?label .  
    ?sample rdfs:subClassOf* ?adultHuman ;        
      rdfs:label ?sampleTypeLabel .  
    FILTER regex(?sample,'-','i')  
    ?adultHuman rdfs:subClassOf _:blankNode .  
    _:blankNode <http://www.w3.org/2002/07/owl#someValuesFrom> ?tissueType .  
    ?tissueType rdfs:label ?tissueTypeLabel .
  }    
  
} order by (?cageClusterLabel)
