PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX biosem_prop: <http://rdf.biosemantics.org/emco/properties/>
PREFIX biosem_dt: <http://rdf.biosemantics.org/emco/datatypes/>


SELECT DISTINCT ?geneUri (xsd:integer(?entrezGeneId) as ?entrezGeneId){

   ?geneUri biosem_prop:altLabel_NO "?ProteinID";
            skos:notation ?entrezGeneId.

FILTER (datatype(?entrezGeneId) = biosem_dt:eg-notation-datatype)

}
